
import React, { useEffect, useState, useCallback } from 'react';
import { Newspaper, RefreshCw, TrendingUp, TrendingDown, Minus, Globe, DollarSign, IndianRupee, AlertTriangle, WifiOff } from 'lucide-react';
import { fetchDailyNews } from '../services/geminiService';
import { NewsItem } from '../types';

const REFRESH_INTERVAL = 5 * 60 * 1000; // 5 minutes

const MarketNews: React.FC = () => {
  const [news, setNews] = useState<NewsItem[]>([]);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);
  const [lastUpdated, setLastUpdated] = useState<string>('');

  const loadNews = useCallback(async () => {
    setLoading(true);
    setError(null);
    try {
      const data = await fetchDailyNews();
      if (data && data.length > 0) {
        setNews(data);
        setLastUpdated(new Date().toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' }));
      } else {
        throw new Error("No news data available");
      }
    } catch (err: any) {
      console.error("Failed to load news", err);
      
      let errorMessage = "Unable to fetch the latest market news.";
      if (err.message?.includes('429') || err.status === 429) {
        errorMessage = "High traffic detected. Please wait a moment and retry.";
      } else if (err.message?.includes('network') || err.message?.includes('fetch')) {
        errorMessage = "Network connection issue. Please check your internet.";
      }
      
      setError(errorMessage);
    } finally {
      setLoading(false);
    }
  }, []);

  useEffect(() => {
    loadNews();
    
    // Auto-refresh every 5 minutes
    const intervalId = setInterval(() => {
      loadNews();
    }, REFRESH_INTERVAL);

    return () => clearInterval(intervalId);
  }, [loadNews]);

  const getSentimentIcon = (sentiment: string) => {
    switch (sentiment) {
      case 'Positive': return <TrendingUp className="w-4 h-4 text-green-500" />;
      case 'Negative': return <TrendingDown className="w-4 h-4 text-red-500" />;
      default: return <Minus className="w-4 h-4 text-slate-400" />;
    }
  };

  const getCategoryIcon = (category: string) => {
    switch (category) {
      case 'Indian Market': return <IndianRupee className="w-4 h-4" />;
      case 'Forex': return <DollarSign className="w-4 h-4" />;
      default: return <Globe className="w-4 h-4" />;
    }
  };

  const getSentimentColor = (sentiment: string) => {
    switch (sentiment) {
      case 'Positive': return 'border-l-4 border-l-green-500';
      case 'Negative': return 'border-l-4 border-l-red-500';
      default: return 'border-l-4 border-l-slate-400';
    }
  };

  return (
    <div className="bg-slate-100 dark:bg-slate-900 py-16 transition-colors duration-300">
      <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
        <div className="flex flex-col md:flex-row justify-between items-center mb-8 gap-4">
          <div>
            <div className="flex items-center gap-2 mb-2">
              <span className="relative flex h-3 w-3">
                <span className="animate-ping absolute inline-flex h-full w-full rounded-full bg-red-400 opacity-75"></span>
                <span className="relative inline-flex rounded-full h-3 w-3 bg-red-500"></span>
              </span>
              <h2 className="text-2xl font-extrabold text-slate-900 dark:text-white">Daily Market Pulse</h2>
            </div>
            <p className="text-sm text-slate-500 dark:text-slate-400">
              Live updates generated by Finwise AI using Google Search {lastUpdated && `• Updated ${lastUpdated}`}
            </p>
          </div>
          
          <button 
            onClick={loadNews}
            disabled={loading}
            className="flex items-center gap-2 px-4 py-2 bg-white dark:bg-slate-800 border border-slate-200 dark:border-slate-700 rounded-lg text-sm font-medium text-slate-700 dark:text-slate-200 hover:bg-slate-50 dark:hover:bg-slate-700 transition-colors disabled:opacity-50 shadow-sm"
          >
            <RefreshCw className={`w-4 h-4 ${loading ? 'animate-spin' : ''}`} />
            {loading ? 'Fetching Live Data...' : 'Refresh News'}
          </button>
        </div>

        {error ? (
          <div className="bg-white dark:bg-slate-800 rounded-xl p-8 text-center border border-red-100 dark:border-red-900/30 shadow-sm max-w-2xl mx-auto">
            <div className="inline-flex items-center justify-center w-16 h-16 bg-red-100 dark:bg-red-900/30 rounded-full mb-4 text-red-600 dark:text-red-400">
              {error.includes('Network') ? <WifiOff className="w-8 h-8" /> : <AlertTriangle className="w-8 h-8" />}
            </div>
            <h3 className="text-lg font-bold text-slate-900 dark:text-white mb-2">Unable to Load News</h3>
            <p className="text-slate-500 dark:text-slate-400 mb-6 max-w-md mx-auto">
              {error}
            </p>
            <button 
              onClick={loadNews}
              className="inline-flex items-center justify-center px-6 py-3 border border-transparent text-base font-medium rounded-md text-white bg-red-600 hover:bg-red-700 transition-colors shadow-lg shadow-red-500/30"
            >
              <RefreshCw className="w-4 h-4 mr-2" />
              Try Again
            </button>
          </div>
        ) : loading ? (
          <div className="grid md:grid-cols-2 lg:grid-cols-4 gap-6">
            {[1, 2, 3, 4].map((i) => (
              <div key={i} className="bg-white dark:bg-slate-800 h-48 rounded-xl shadow-sm animate-pulse p-6 border border-slate-100 dark:border-slate-700">
                <div className="flex justify-between mb-4">
                   <div className="h-5 bg-slate-200 dark:bg-slate-700 rounded w-1/3"></div>
                   <div className="h-4 bg-slate-200 dark:bg-slate-700 rounded w-1/4"></div>
                </div>
                <div className="h-4 bg-slate-200 dark:bg-slate-700 rounded w-full mb-2"></div>
                <div className="h-4 bg-slate-200 dark:bg-slate-700 rounded w-5/6 mb-4"></div>
                <div className="mt-auto h-4 bg-slate-200 dark:bg-slate-700 rounded w-1/4"></div>
              </div>
            ))}
          </div>
        ) : (
          <div className="grid md:grid-cols-2 lg:grid-cols-4 gap-6">
            {news.map((item, index) => (
              <div 
                key={index} 
                className={`bg-white dark:bg-slate-800 rounded-xl p-6 shadow-sm hover:shadow-xl transition-all duration-300 flex flex-col ${getSentimentColor(item.sentiment)}`}
              >
                <div className="flex justify-between items-start mb-4">
                  <span className="inline-flex items-center gap-1 px-2.5 py-1 rounded-full text-xs font-semibold bg-slate-100 dark:bg-slate-700 text-slate-700 dark:text-slate-200">
                    {getCategoryIcon(item.category)}
                    {item.category}
                  </span>
                  <span className="text-[10px] font-medium text-slate-400 uppercase tracking-wider">{item.timestamp}</span>
                </div>
                
                <h3 className="font-bold text-slate-900 dark:text-white mb-3 line-clamp-2 leading-tight">
                  {item.headline}
                </h3>
                
                <p className="text-sm text-slate-600 dark:text-slate-400 line-clamp-3 mb-4 flex-grow">
                  {item.summary}
                </p>

                <div className="flex items-center gap-2 text-xs font-medium border-t border-slate-100 dark:border-slate-700 pt-4 mt-auto">
                  <span className="text-slate-500">Market Sentiment:</span>
                  <span className={`flex items-center gap-1 ${
                    item.sentiment === 'Positive' ? 'text-green-600 dark:text-green-400' : 
                    item.sentiment === 'Negative' ? 'text-red-600 dark:text-red-400' : 'text-slate-500 dark:text-slate-400'
                  }`}>
                    {getSentimentIcon(item.sentiment)}
                    {item.sentiment}
                  </span>
                </div>
              </div>
            ))}
          </div>
        )}
        
        <div className="mt-8 text-center">
           <span className="inline-flex items-center gap-1.5 text-xs font-medium text-slate-400 bg-white dark:bg-slate-800 px-3 py-1.5 rounded-full shadow-sm border border-slate-100 dark:border-slate-700">
             <Newspaper className="w-3 h-3" />
             AI-Curated Market Highlights
           </span>
        </div>
      </div>
    </div>
  );
};

export default MarketNews;
